services:
  caddy:
    container_name: caddy
    image: docker.io/library/caddy:2-alpine
    restart: unless-stopped
    networks:
      - open-webui-bridge
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./assets/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    pull_policy: always
    restart: unless-stopped
    volumes:
      - open-webui:/app/backend/data
    networks:
      - open-webui-bridge
    environment:
      - PORT=${OPENWEBUI_PORT:-8080}
      - HOST=0.0.0.0
      - OPENAI_API_BASE_URL=http://bedrock-access-gateway:${BEDROCK_ACCESS_GATEWAY_PORT:-8000}/api/v1
      - OPENAI_API_KEY=bedrock
      - ENABLE_OLLAMA_API=True
      - OLLAMA_BASE_URL=http://ollama-server:11434
      - DEFAULT_MODELS=${LOCAL_MODEL:-hf.co/unsloth/gemma-3-4b-it-GGUF:Q4_K_M}
      - REDIS_URL=redis://valkey-server:6379/0
      - SEARXNG_QUERY_URL=http://searxng-server:${SEARXNG_PORT:-8888}/search?q=<query>
      - USE_CUDA_DOCKER=True
      - MODELS_CACHE_TTL=1210000
      - ENABLE_WEB_SEARCH=True
      - WEB_SEARCH_ENGINE=searxng
      - WEB_SEARCH_TRUST_ENV=True
      - WEB_SEARCH_RESULT_COUNT=3
      - WEB_SEARCH_CONCURRENT_REQUESTS=10
      - BYPASS_EMBEDDING_AND_RETRIEVAL=${BYPASS_EMBEDDING_AND_RETRIEVAL:-True}

  bedrock-access-gateway:
    container_name: bedrock-access-gateway
    build:
      context: https://github.com/aws-samples/bedrock-access-gateway.git#main:src
      dockerfile: Dockerfile_ecs
    restart: unless-stopped
    networks:
      - open-webui-bridge
    environment:
      - PORT=${BEDROCK_ACCESS_GATEWAY_PORT:-8000}
      - AWS_REGION=${AWS_REGION:-us-west-2}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  ollama-server:
    container_name: ollama-server
    image: ollama/ollama:latest
    pull_policy: always
    entrypoint: [ "/bin/bash", "/entrypoint.sh" ]
    tty: true
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
      - ./assets/ollama/entrypoint.sh:/entrypoint.sh
    networks:
      - open-webui-bridge
    environment:
      - OLLAMA_WEBAPI_PORT=${OLLAMA_WEBAPI_PORT:-11434}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LOCAL_MODEL=${LOCAL_MODEL:-hf.co/unsloth/gemma-3-4b-it-GGUF:Q4_K_M}

  valkey-server:
    container_name: valkey-server
    image: valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - valkey:/data
    networks:
      - open-webui-bridge

  searxng-server:
    container_name: searxng-server
    image: ghcr.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - open-webui-bridge
    volumes:
      - searxng:/var/cache/searxng
      - ./assets/searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://searxng-server:${SEARXNG_PORT:-8888}/
      - SEARXNG_SECRET=${SEARXNG_SECRET:-somesearxngsecret}
      - SEARXNG_LIMITER=False
      - SEARXNG_PUBLIC_INSTANCE=False
      - GRANIAN_PORT=${SEARXNG_PORT:-8888}

networks:
  open-webui-bridge:
    name: open-webui-bridge
    driver: bridge

volumes:
  ollama: {}
  open-webui: {}
  valkey: {}
  searxng: {}
