services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    pull_policy: always
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - open-webui:/app/backend/data
    networks:
      - proxy
    ports:
      - ${OPENWEBUI_PORT:-8080}:${OPENWEBUI_PORT:-8080}
    expose:
      - ${OPENWEBUI_PORT:-8080}
    environment:
      - PORT=${OPENWEBUI_PORT:-8080}
      - OPENAI_API_BASE_URL=http://bedrock-access-gateway/api/v1
      - OPENAI_API_KEY=bedrock
      - ENABLE_OLLAMA_API=True
      - OLLAMA_BASE_URL=http://ollama-server:11434
      - DEFAULT_MODELS=hf.co/unsloth/gemma-3-4b-it-GGUF:Q4_K_M
      - USE_CUDA_DOCKER=True
      - MODELS_CACHE_TTL=1210000
      - ENABLE_WEB_SEARCH=True
      - WEB_SEARCH_ENGINE=searxng
      - WEB_SEARCH_RESULT_COUNT=10
      - SEARXNG_QUERY_URL=http://searxng-server:${SEARXNG_PORT:-8888}/search?q=<query>

  bedrock-access-gateway:
    build:
      context: https://github.com/aws-samples/bedrock-access-gateway.git#main:src
      dockerfile: Dockerfile_ecs
    container_name: bedrock-access-gateway
    restart: unless-stopped
    networks:
      - proxy
    expose:
      - ${BEDROCK_ACCESS_GATEWAY_PORT:-8000}:80
    environment:
      - AWS_REGION=${AWS_REGION:-us-west-2}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  ollama-server:
    image: ollama/ollama:latest
    pull_policy: always
    container_name: ollama-server
    entrypoint: [ "/bin/bash", "/entrypoint.sh" ]
    tty: true
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
      - ./assets/ollama/entrypoint.sh:/entrypoint.sh
    networks:
      - proxy
    expose:
      - ${OLLAMA_WEBAPI_PORT:-11434}:${OLLAMA_WEBAPI_PORT:-11434}
    environment:
      - OLLAMA_WEBAPI_PORT=${OLLAMA_WEBAPI_PORT:-11434}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  valkey-server:
    container_name: valkey-server
    image: valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - valkey:/data
    networks:
      - proxy
    expose:
      - 6379

  searxng-server:
    container_name: searxng-server
    image: ghcr.io/searxng/searxng:2025.8.12-6b1516d
    restart: unless-stopped
    networks:
      - proxy
    expose:
      - ${SEARXNG_PORT:-8888}
    volumes:
      - searxng:/var/cache/searxng
      - ./assets/searxng/:/etc/searxng/:rw
    environment:
      - SEARXNG_BASE_URL=https://127.0.0.1:${SEARXNG_PORT:-8888}/
      - SEARXNG_SECRET=${SEARXNG_SECRET:-somesearxngsecret}
      - SEARXNG_LIMITER=False
      - SEARXNG_PUBLIC_INSTANCE=False
      - GRANIAN_PORT=${SEARXNG_PORT:-8888}

networks:
  proxy:
    name: open-webui-proxy
    driver: bridge

volumes:
  ollama: {}
  open-webui: {}
  valkey: {}
  searxng: {}
